### PR TITLE
Ignore MacOS `psn` commandline argument

### LINKED ISSUE #90: MacOS / Darwin program serial number causes trivrost start to fail
**Describe the bug**
When launching trivrost in the latest MacOS version from the GUI, the system may append a program serial number to the commandline.
It looks like `--psn_0_12345` and since it is an unrecognized parameter, trivrost will fail to launcher. This is only after the GateKeeper confirmation dialog and does not happen on relaunch.

**To Reproduce**
Download a newly built, previously unknown trivrost launcher.

**Screenshots**
image

**Additional context**
This trivrost behavior was introduced in version 1.3.2

### PR DESCRIPTION
**Pull request by dragetd**
MacOS adds a socalled program serial number when the application was launched
through a GUI like Gatekeeper. Since v1.3.2 we raise an error for unkown
arguments. This patch removes such parameter before parsing the rest.

Fixes #90

### CODE REVIEW

**Comment by ma-assbrock** [comment]
You should add an if-statement and execute your code only on macOS, as your changelog entry suggests.

**Comment by dragetd** [comment]
May I rather change the changelog? :-P I think filtering this args does not hurt on the other platforms.

File: cmd/launcher/flags/flags.go [hunk 1]
```diff
@@ -44,6 +45,14 @@ const (
 
 func Setup(args []string) (*LauncherFlags, error) {
 	launcherFlags := LauncherFlags{nextLogIndex: -1}
+
+	// MacOS might append program serial number which we have to ignore/remove from args
+	ignoredArgsExp, _ := regexp.Compile("-+psn.*")
+	for i, arg := range args {
+		if (ignoredArgsExp.MatchString(arg)) {
+			args = append(args[:i], args[i+1:]...)
```
Comment (MMulthaupt) [inline cmd/launcher/flags/flags.go]:
```suggestion
			args = append(args[:i], args[i+1:]...)
			break
```
